parameters:
#    jrojo_club.example.class: Jrojo\ClubBundle\Example

services:
#    jrojo_club.example:
#        class: %jrojo_club.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
