# src/Jrojo/HelloBundle/Resources/config/routing.yml
hello:
    path:    /hello/{name}
    defaults: { _controller: JrojoHelloBundle:Hello:index }

jrojo_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: JrojoHelloBundle:Default:index }
