parameters:
#    jrojo_hello.example.class: Jrojo\HelloBundle\Example

services:
#    jrojo_hello.example:
#        class: %jrojo_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
