# src/Jrojo/AccountBundle/Resources/config/routing.yml
jrojo_account_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: JrojoAccountBundle:Default:index }
account_register:
    pattern: /register
    defaults: { _controller: JrojoAccountBundle:Account:register }

account_create:
    pattern: /register/create
    defaults: { _controller: JrojoAccountBundle:Account:create }

account_login:
    pattern: /login
    defaults: { _controller: JrojoAccountBundle:Account:login }
    
account_check:
    pattern: /login/check
    defaults: { _controller: JrojoAccountBundle:Account:check }
    